### ISSUE TITLE
'retry' is not exported from 'get-it/middleware' (imported as 'retry').

### ISSUE THREAD

**Issue by ahmedrizwan239** [sanity-io/get-it#478] opened 2024-06-27 22:13 UTC
**Failed to compile when deploying on vercel - Nextjs 13**

It shows errors, like:
Attempted import error: 'retry' is not exported from 'get-it/middleware' (imported as 'retry').
similarly other modules also have this issue that are imported from get-it/middleware. Im

**To Reproduce**
Not applicable

**Expected behavior**
App should build and deploy successfully..

**Screenshots**
![image](https://github.com/sanity-io/get-it/assets/112283994/6f781156-9daa-4c7b-b879-f9006d99f1f4)

**Which versions of Sanity are you using?**
"sanity": "^3.48.1",

**Which versions of Node.js / npm are you running?**
"@types/node": "^20.8.8",

Run `npm -v && node -v` in the terminal and copy-paste the result here.
I'm not running locally but deploying on vercel.

**Additional context**
Im using nextjs 13, and it get stuck here only when deploying. it is working fine on dev mode.

**Comment by stipsan** [comment] 2024-07-08 11:56
Closing this since there are no instructions for how to reproduce, or a link to a github repo that demonstrates the problem.
Feel free to open a new issue, and make sure you fill in all the information necessary so that others can see the same error you're seeing, and then be able to debug it and test possible bugfixes 😄

**Closed by stipsan** 2024-07-08 11:56 UTC
